version: '3.2'
services:
  nginx:
    ports:
      - '80:80'
    build:
      context: .
    networks:
      - reverseproxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=mwcm.ca"
      - "traefik.frontend.rule=Host:mwcm.ca"
      - "traefik.docker.network=reverseproxy_reverseproxy"

networks:
  reverseproxy:
    external:
      name: reverseproxy_reverseproxy
